name: Deploy

on:
  push:
    branches: 
    - main

jobs:
  build:
    run-on: ubuntu-latest
    steps:
      uses: actions/checkout@v2
      uses: actions/setup-node@v2
      name: Install depencedies
      run: npm install
      name: build Website
      run: npm run build
      name: Set AWS credentials
      uses: aws-actions/configue-aws-credentials@v1
      with:
        aws-access-key-id: ${"AKIAVOEO5HDHIAP33GF7"}
        aws-secret-access-key: ${"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"}
        aws-region: us-west-1
      name: Copy to S3
        run: aws s3 sync ./build/. s3://cleanvegasinitiative.org
